os: linux
language: node_js
cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - v12
  - v10

install:
  - yarn install

script:
  - yarn lint
  - yarn test
  - yarn coveralls <./coverage/lcov.info
